AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFront Function for converting URI into a query parameter. 
  The input URI must be in the following format: <PathPrefix>/<Resource>.
  It is rewritten to :
  <TargetURI>?<QueryKey>=<Resource>

Parameters:
  PathPrefix:
    Type: String
    Description: Prefix in the URI path. Must start with '/'.
  QueryKey:
    Type: String
    Default: file
    Description: Query key for the resource name contained in the URI.
  TargetURI:
    Type: String
    Default: /signin.html
    Description: Target URI
  FunctionName:
    Type: String
    Description: Name of the function

Resources:
  RewriteQueryFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Ref FunctionName
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          event.request.querystring["${QueryKey}"] = event.request.uri.replace("${PathPrefix}/", "");;
          event.request.uri = "${TargetURI}";
          return event.request;
        }
      FunctionConfig:
        Comment: !Sub "rewrite ${PathPrefix}/<resource> into ${TargetURI}?${QueryKey}=<resource>"
        Runtime: cloudfront-js-1.0

Outputs:
  FunctionARN:
    Value: !GetAtt RewriteQueryFunction.FunctionARN
    Description: ARN of the function
