AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFront Function for rewriting request URI

Parameters:
  PathPrefix:
    Type: String
    Description: >
      Prefix that needs to be removed from the URI path. Must start with '/'.
      For example, with PathPrefix="/public/content" the URI "/public/content/index.html" will become "/index.html".
  FunctionName:
    Type: String
    Description: Name of the function

Resources:
  RewriteRequestFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Ref FunctionName
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          event.request.uri = event.request.uri.replace("${PathPrefix}", "");
          return event.request;
        }
      FunctionConfig:
        Comment: !Sub "remove prefix ${PathPrefix} from request URI"
        Runtime: cloudfront-js-1.0

Outputs:
  FunctionARN:
    Value: !GetAtt RewriteRequestFunction.FunctionARN
    Description: ARN of the function
