AWSTemplateFormatVersion: 2010-09-09
Description: Create user with programmatic access limited to one S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Unique name for S3 Bucket

  NewUserName:
    Type: String
    Description: Name of the user you wish to Create

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName

  NewUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref NewUserName
      Policies:
        - PolicyName: !Sub "${NewUserName}-can-access-${BucketName}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub "arn:aws:s3:::${Bucket}"
                  - !Sub "arn:aws:s3:::${Bucket}/*"

  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref NewUser

Outputs:
  AccessKey:
    Value: !Ref UserAccessKey
  SecretKey:
    Value: !GetAtt UserAccessKey.SecretAccessKey
