version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multi-origin-cloudfront"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xjmpe478ykv0"
s3_prefix = "multi-origin-cloudfront"
region = "us-east-1"
profile = "sam"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
