AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Nested SAM Application

Resources:
  PublicRequestRewriteFunction:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cloudfront-rewrite-query-function.yaml
      Parameters:
        FunctionName: query-rewrite
        PathPrefix: /protected

Outputs:
  FunctionARN:
    Value: !GetAtt PublicRequestRewriteFunction.Outputs.FunctionARN
    Description: CloudFront Function ARN
