version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nested"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xjmpe478ykv0"
s3_prefix = "nested"
region = "us-east-1"
profile = "sam"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
image_repositories = []
